default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "sanin_legacy") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "development_password") %>

development:
  <<: *default
  database: sanin_legacy_development

test:
  <<: *default
  database: sanin_legacy_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "sanin_legacy_production") %>
  host: <%= (ENV["RAILS_ENV"] == "production") ? ENV.fetch("DATABASE_HOST") { raise "DATABASE_HOST is required in production" } : ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= (ENV["RAILS_ENV"] == "production") ? ENV.fetch("DATABASE_PORT") { raise "DATABASE_PORT is required in production" } : ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= (ENV["RAILS_ENV"] == "production") ? ENV.fetch("DATABASE_USER") { raise "DATABASE_USER is required in production" } : ENV.fetch("DATABASE_USER", "sanin_legacy") %>
  password: <%= (ENV["RAILS_ENV"] == "production") ? ENV.fetch("DATABASE_PASSWORD") { raise "DATABASE_PASSWORD is required in production" } : ENV.fetch("DATABASE_PASSWORD", "development_password") %>
